import jsPDF from 'jspdf';

// ตัวช่วย: แปลงข้อความภาษาไทยให้ jsPDF รองรับ (ใช้ encoding แบบ latin)
// jsPDF ไม่รองรับ Unicode โดยตรง — ใช้ html2canvas แทนสำหรับ Thai text
// ฟังก์ชันนี้ใช้วิธี canvas snapshot ของ DOM element

/**
 * Export Daily Reading to PDF
 * @param {object} card - ไพ่ที่จับได้
 * @param {object} category - หมวดหมู่ที่เลือก
 * @param {string} meaning - ความหมายของไพ่
 */
export const exportDailyReadingToPDF = async (card, category, meaning) => {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  const currentDate = new Date().toLocaleDateString('th-TH', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  // ---- พื้นหลัง gradient จำลอง ----
  pdf.setFillColor(30, 41, 59); // slate-800
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // ---- Header bar ----
  pdf.setFillColor(49, 46, 129); // indigo-900
  pdf.rect(0, 0, pageWidth, 40, 'F');

  // ---- Title ----
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(18);
  pdf.setTextColor(250, 204, 21); // yellow-400
  pdf.text('Tarot Daily Reading', pageWidth / 2, 16, { align: 'center' });

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(11);
  pdf.setTextColor(203, 213, 225); // slate-300
  pdf.text(currentDate, pageWidth / 2, 26, { align: 'center' });

  if (category) {
    pdf.setFontSize(10);
    pdf.setTextColor(147, 197, 253); // blue-300
    pdf.text(`Category: ${category.name}`, pageWidth / 2, 35, { align: 'center' });
  }

  // ---- Card image ----
  let imageLoaded = false;
  try {
    const img = await loadImageAsBase64(card.image);
    if (img) {
      const imgX = pageWidth / 2 - 20;
      const imgY = 50;
      pdf.addImage(img, 'PNG', imgX, imgY, 40, 60);
      if (card.isReversed) {
        // วาดกรอบสีแดงถ้ากลับหัว
        pdf.setDrawColor(239, 68, 68);
        pdf.setLineWidth(0.8);
        pdf.rect(imgX, imgY, 40, 60);
      }
      imageLoaded = true;
    }
  } catch (_) {
    imageLoaded = false;
  }

  const afterImageY = imageLoaded ? 120 : 55;

  // ---- Card name ----
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(16);
  pdf.setTextColor(250, 204, 21); // yellow-400
  pdf.text(card.nameTh || card.name, pageWidth / 2, afterImageY, { align: 'center' });

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(11);
  pdf.setTextColor(148, 163, 184); // slate-400
  pdf.text(card.name, pageWidth / 2, afterImageY + 8, { align: 'center' });

  if (card.isReversed) {
    pdf.setFontSize(9);
    pdf.setTextColor(252, 165, 165); // red-300
    pdf.text('[ Reversed ]', pageWidth / 2, afterImageY + 16, { align: 'center' });
  }

  // ---- Divider ----
  const divY = afterImageY + (card.isReversed ? 22 : 16);
  pdf.setDrawColor(99, 102, 241); // indigo-500
  pdf.setLineWidth(0.5);
  pdf.line(margin, divY, pageWidth - margin, divY);

  // ---- Meaning section ----
  let yPos = divY + 10;

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(12);
  pdf.setTextColor(167, 139, 250); // violet-400
  pdf.text('Meaning / คำทำนาย', margin, yPos);
  yPos += 8;

  // วาดกล่องพื้นหลัง
  const meaningText = meaning || '-';
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(226, 232, 240); // slate-200

  // แปลงข้อความ (ภาษาไทยจะแสดงเป็น fallback characters ใน jsPDF)
  const lines = pdf.splitTextToSize(meaningText, contentWidth);
  const boxHeight = lines.length * 5.5 + 10;

  pdf.setFillColor(51, 65, 85); // slate-700
  pdf.roundedRect(margin, yPos - 4, contentWidth, boxHeight, 3, 3, 'F');

  pdf.text(lines, margin + 5, yPos + 3);
  yPos += boxHeight + 10;

  // ---- Card info ----
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  pdf.setTextColor(100, 116, 139); // slate-500
  pdf.text(`Card #${card.id} of 78  |  ${card.isReversed ? 'Reversed' : 'Upright'}`, margin, yPos);

  // ---- Footer ----
  pdf.setFillColor(15, 23, 42); // slate-950
  pdf.rect(0, pageHeight - 14, pageWidth, 14, 'F');
  pdf.setFontSize(8);
  pdf.setTextColor(100, 116, 139);
  pdf.text('Generated by Tarot Reading App', pageWidth / 2, pageHeight - 5, { align: 'center' });

  // ---- Save ----
  const safeDate = new Date().toISOString().slice(0, 10);
  pdf.save(`tarot-daily-${safeDate}.pdf`);
};

/**
 * Export Monthly Reading (10 cards) to PDF
 * @param {Array} selectedCards - ไพ่ 10 ใบที่เลือก
 * @param {Function} getPositionMeaning - ฟังก์ชันดึงความหมายตามตำแหน่ง
 * @param {Array} positionLabels - ป้ายชื่อตำแหน่ง 10 ตำแหน่ง
 */
export const exportMonthlyReadingToPDF = async (selectedCards, getPositionMeaning, positionLabels) => {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  const currentDate = new Date().toLocaleDateString('th-TH', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  // ======== หน้าปก ========
  pdf.setFillColor(15, 23, 42);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // gradient bar
  pdf.setFillColor(49, 46, 129);
  pdf.rect(0, 0, pageWidth, 60, 'F');

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(22);
  pdf.setTextColor(250, 204, 21);
  pdf.text('Tarot Monthly Reading', pageWidth / 2, 25, { align: 'center' });

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(13);
  pdf.setTextColor(203, 213, 225);
  pdf.text('10-Card Celtic Cross Spread', pageWidth / 2, 38, { align: 'center' });
  pdf.text(currentDate, pageWidth / 2, 52, { align: 'center' });

  // สรุปไพ่ทั้ง 10 ใบในหน้าปก
  let yPos = 75;
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(12);
  pdf.setTextColor(167, 139, 250);
  pdf.text('Card Summary', margin, yPos);
  yPos += 8;

  selectedCards.forEach((card, idx) => {
    const pos = positionLabels[idx];
    if (yPos > pageHeight - 20) return; // ป้องกัน overflow

    pdf.setFillColor(30, 41, 59);
    pdf.roundedRect(margin, yPos - 3, contentWidth, 10, 2, 2, 'F');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8);
    pdf.setTextColor(250, 204, 21);
    pdf.text(`${idx + 1}.`, margin + 2, yPos + 4);

    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(226, 232, 240);
    pdf.text(`${pos.label}`, margin + 8, yPos + 4);

    pdf.setTextColor(148, 163, 184);
    const cardLabel = `${card.nameTh}${card.isReversed ? ' (R)' : ''}`;
    pdf.text(cardLabel, pageWidth - margin - 2, yPos + 4, { align: 'right' });

    yPos += 12;
  });

  // footer ปก
  pdf.setFillColor(15, 23, 42);
  pdf.rect(0, pageHeight - 14, pageWidth, 14, 'F');
  pdf.setFontSize(8);
  pdf.setTextColor(100, 116, 139);
  pdf.text('Generated by Tarot Reading App', pageWidth / 2, pageHeight - 5, { align: 'center' });

  // ======== หน้าละ 1 ใบ ========
  for (let i = 0; i < selectedCards.length; i++) {
    pdf.addPage();

    const card = selectedCards[i];
    const pos = positionLabels[i];
    const meaning = getPositionMeaning(card.id, i);

    // พื้นหลัง
    pdf.setFillColor(30, 41, 59);
    pdf.rect(0, 0, pageWidth, pageHeight, 'F');

    // Header bar
    pdf.setFillColor(49, 46, 129);
    pdf.rect(0, 0, pageWidth, 35, 'F');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.setTextColor(147, 197, 253);
    pdf.text(`Position ${pos.position} of 10`, margin, 13);

    pdf.setFontSize(13);
    pdf.setTextColor(250, 204, 21);
    pdf.text(pos.label, margin, 24);

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    pdf.setTextColor(148, 163, 184);
    pdf.text(pos.description, margin, 32);

    // Page number (top right)
    pdf.setFontSize(9);
    pdf.setTextColor(100, 116, 139);
    pdf.text(`${i + 1} / ${selectedCards.length}`, pageWidth - margin, 13, { align: 'right' });

    // Card image
    let imgLoaded = false;
    try {
      const img = await loadImageAsBase64(card.image);
      if (img) {
        const imgX = pageWidth / 2 - 18;
        const imgY = 42;
        pdf.addImage(img, 'PNG', imgX, imgY, 36, 54);
        if (card.isReversed) {
          pdf.setDrawColor(239, 68, 68);
          pdf.setLineWidth(0.8);
          pdf.rect(imgX, imgY, 36, 54);
        }
        imgLoaded = true;
      }
    } catch (_) {}

    const afterImg = imgLoaded ? 104 : 45;

    // Card name
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(15);
    pdf.setTextColor(250, 204, 21);
    pdf.text(card.nameTh || card.name, pageWidth / 2, afterImg, { align: 'center' });

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.setTextColor(148, 163, 184);
    pdf.text(card.name, pageWidth / 2, afterImg + 7, { align: 'center' });

    if (card.isReversed) {
      pdf.setFontSize(8);
      pdf.setTextColor(252, 165, 165);
      pdf.text('[ Reversed / กลับหัว ]', pageWidth / 2, afterImg + 14, { align: 'center' });
    }

    // Divider
    const divY2 = afterImg + (card.isReversed ? 20 : 13);
    pdf.setDrawColor(99, 102, 241);
    pdf.setLineWidth(0.4);
    pdf.line(margin, divY2, pageWidth - margin, divY2);

    // Meaning
    let yp = divY2 + 8;
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.setTextColor(167, 139, 250);
    pdf.text('Meaning / คำทำนาย', margin, yp);
    yp += 6;

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9.5);
    pdf.setTextColor(226, 232, 240);
    const lines = pdf.splitTextToSize(meaning || '-', contentWidth - 8);
    const boxH = lines.length * 5.2 + 10;

    pdf.setFillColor(51, 65, 85);
    pdf.roundedRect(margin, yp - 3, contentWidth, boxH, 3, 3, 'F');
    pdf.text(lines, margin + 4, yp + 4);
    yp += boxH + 6;

    // Card info
    pdf.setFontSize(8);
    pdf.setTextColor(100, 116, 139);
    pdf.text(`Card #${card.id} of 78  |  ${card.isReversed ? 'Reversed' : 'Upright'}`, margin, yp);

    // Footer
    pdf.setFillColor(15, 23, 42);
    pdf.rect(0, pageHeight - 14, pageWidth, 14, 'F');
    pdf.setFontSize(8);
    pdf.setTextColor(100, 116, 139);
    pdf.text('Generated by Tarot Reading App', pageWidth / 2, pageHeight - 5, { align: 'center' });
  }

  // Save
  const safeDate = new Date().toISOString().slice(0, 10);
  pdf.save(`tarot-monthly-${safeDate}.pdf`);
};

// ---- Helper: โหลดรูปภาพเป็น base64 ----
const loadImageAsBase64 = (src) => {
  return new Promise((resolve, reject) => {
    if (!src) return reject(new Error('No src'));
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth || img.width;
        canvas.height = img.naturalHeight || img.height;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL('image/png'));
      } catch (e) {
        reject(e);
      }
    };
    img.onerror = () => reject(new Error('Image load failed'));
    img.src = src;
  });
};
